#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(File.realpath(__FILE__)) + '/../lib')

require 'plotit'
require 'slop'

opts = Slop.parse do |o|
  o.string '-l', '--layout', 'The layout (date_string_number, string_number, string, date_string)'
  o.string '-f', '--formula', 'The formula (count, avg, sum)'
  o.string '-t', '--truncate', 'Truncate date at (sec, min, hour, day, month, year)'
  o.integer '-s', '--sort', 'Sort by column position'
  o.string '--sort-dir', 'Sort direction', default: 'desc'
  o.string '--output-format', 'Output format (text, table)', default: 'text'

  o.on '--version', 'print the version' do
    puts Potit::VERSION
    exit
  end
end

raise "selecte layout" unless opts[:layout].present?

Plotit::Cli.new({}).groupped(STDIN, STDOUT, opts.to_hash)
